---
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    hostname: ${VIRTUAL_HOST}
    container_name: unifi-network-application
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    env_file: .env
    volumes:
      - ./data/unifi-network-application/:/config/data/
      - ./logs/unifi-network-application/:/logs/
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514 #optional
    restart: unless-stopped

  mongo:
    image: mongo:4.4.18
    container_name: mongo
    user: 1000:1000
    env_file: .env
    volumes:
      - ./data/mongo:/data/db
      - ./config/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    restart: unless-stopped

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.0-arm64
    volumes:
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/unifi:/var/log/unifi
