---
version: '3'
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    hostname: ${VIRTUAL_HOST}
    container_name: unifi-controller
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ./unifi/data/:/config/data/
      - ./unifi/logs/:/logs/
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514 #optional
    restart: unless-stopped

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.0-arm64
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./unifi/logs:/var/log/unifi
