---
filebeat.inputs:
- type: log
  paths:
    - /var/log/unifi/*.log


filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3
  #index.codec: best_compression
  #_source.enabled: false

setup.kibana:
  host: "kibana.themitchell.co.uk"

output.logstash:
  hosts: ["192.168.0.11:5044"] # TODO: replace with static domain name
  index: unifi-logs
